[
    "Iso Propyl Alcohol",
    "N-Propanol",
    "Iso Butyl Alcohol - IsoButanol",
    "N-Butanol",
    "Prop-BH",
    "Methanol",
    "Ethanol ",
    "Mono Ethylene Glycol",
    "Di Ethylene Glycol",
    "Tri Ethylene Glycol",
    "Propylene Glycol",
    "Ethylene Glycol MonoButyl Ether -Butyl Glycol",
    "Ethylene Glycol MonoEthyl Ether -Ethyl Glycol",
    "Butyl Carbitol",
    "Methyl IsoButyl Ketone",
    "Methyl Ethyl Ketone",
    "Dimethylformamide",
    "White Spirit",
    "White Oil",
    "Methylene Chloride - Dichloromethane",
    "Chloroform - Trichloromethane",
    "Ethylene Dichloride",
    "Trichloroethylene",
    "Perchloroethylene",
    "Dichloropropane",
    "Mixed Xylene",
    "Toluene",
    "Phthalic Anhydride",
    "Phenol",
    "Acetone",
    "Cyclohexanone",
    "Styrene Monomer",
    'Linear Alkyl Benzene',
    "Benzoic Acid",
    "Phosphoric Acid",
    "Sodium Acid Pyrophosphate",
    "Sodium Tripolyphosphate",
    "Tri Sodium Phosphate",
    "Mono Potassium Phosphate",
    "Mono Ammonium Phosphate",
    "Di Ammonium Phosphate",
    'Di Calcium Phosphate',
    "Oxalic Acid",
    "Pumice Stones",
    "Sulphur Black",
    "Chromic Acid Trihydrate",
    "Sodium Dichromate Anhydrous",
    "Acrylamide",
    "Gum Rosin",
    "Terpineol",
    "Dipentene",
    "Pine Oil",
    "Potassium Hydroxide",
    "Ferrous Sulphate Mono",
    "Sulphate of Potash",
    "Copper Sulphate PentaHydrate",
    "Sodium Lauryl Ether Sulphate",
    "Linear Alkyl Benzene Sulphonic Acid - LABSA",
    "Linear Alkyl Benzene",
    'Glycerin',
    "Stearic Acid",
    "Nitric Acid",
    "Sodium Nitrite",
    "Sodium Nitrate",
    "Ammonium Nitrate",
    "Borax DecaHydrate",
    "Borax PentaHydrate",
    "Boric Acid",
    "Hydrofluoric Acid",
    "Ammonium Bi Fluoride",
    "Sodium Fluoride",
    "Ammonium Sulphate",
    "Ammonium Chloride",
    "Aluminium Sulphate",
    "Glacial Acetic Acid",
    "Formic Acid",
    "Sodium Acetate",
    "Sodium Formate",
    "Sodium Hydro Sulphite",
    "Hydrogen Peroxide ",
    "Sodium Sulphide Flakes Red / yellow",
    "Sodium Sulphate Anhydrous",
    "Sodium Metabisulphite",
    "Sodium Bi Sulphate",
    "Soda Ash",
    "Sodium Bi Carbonate",
    "Caustic Soda"
]
